feat: add snippet_constant_cb.cpp file, for now it's a temporary file and make no contributions to sdpa logic, even the file itself is not complete for now. refactor: update compute_sdpa.cpp, now we have a complete sdpa computation logic update simgle_ring_sdpa.cpp to accommodate compute_sdpa.cpp, but there is a bug: 	error: use of undeclared identifier 'EnqueueWriteBuffer'   147 |     EnqueueWriteBuffer(device->command_queue(), scaler_buffer, full_scaler_data, true); in simple_ring_sdpa.cpp
Changes to be committed:
	modified:   kernels/compute_sdpa.cpp
	modified:   main.cpp
	modified:   simple_ring_sdpa.cpp
	new file:   snippet_constant_cb.cpp